/*
 * Bill Pay Exchange Biller Management API
 * Biller Management Service
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Bill_Pay_Development_Support@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.developer.biller_management_client.model;

import org.junit.Test;


/**
 * Model tests for BillerManagementRequest
 */
public class BillerManagementRequestTest {
    private final BillerManagementRequest model = new BillerManagementRequest();

    /**
     * Model tests for BillerManagementRequest
     */
    @Test
    public void testBillerUploadRequest() {
        // TODO: test BillerManagementRequest
    }

    /**
     * Test the property 'action'
     */
    @Test
    public void actionTest() {
        // TODO: test action
    }

    /**
     * Test the property 'effectiveDate'
     */
    @Test
    public void effectiveDateTest() {
        // TODO: test effectiveDate
    }

    /**
     * Test the property 'general'
     */
    @Test
    public void generalTest() {
        // TODO: test general
    }

    /**
     * Test the property 'serviceRelationships'
     */
    @Test
    public void serviceRelationshipsTest() {
        // TODO: test serviceRelationships
    }

    /**
     * Test the property 'cardPaymentSupport'
     */
    @Test
    public void cardPaymentSupportTest() {
        // TODO: test cardPaymentSupport
    }

    /**
     * Test the property 'convenienceFees'
     */
    @Test
    public void convenienceFeesTest() {
        // TODO: test convenienceFees
    }

    /**
     * Test the property 'serviceAreas'
     */
    @Test
    public void serviceAreasTest() {
        // TODO: test serviceAreas
    }

    /**
     * Test the property 'consumerAuths'
     */
    @Test
    public void consumerAuthsTest() {
        // TODO: test consumerAuths
    }

    /**
     * Test the property 'deactivation'
     */
    @Test
    public void deactivationTest() {
        // TODO: test deactivation
    }

}
