/*
 * Bill Pay Exchange Biller Management API
 * Biller Management Service
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Bill_Pay_Development_Support@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.developer.biller_management_client.model;

import org.junit.Test;


/**
 * Model tests for BillerManagementResponse
 */
public class BillerManagementResponseTest {
    private final BillerManagementResponse model = new BillerManagementResponse();

    /**
     * Model tests for BillerManagementResponse
     */
    @Test
    public void testBillerUploadResponse() {
        // TODO: test BillerManagementResponse
    }

    /**
     * Test the property 'action'
     */
    @Test
    public void actionTest() {
        // TODO: test action
    }

    /**
     * Test the property 'billerId'
     */
    @Test
    public void billerIdTest() {
        // TODO: test billerId
    }

    /**
     * Test the property 'statusIndicator'
     */
    @Test
    public void statusIndicatorTest() {
        // TODO: test statusIndicator
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'workRequestId'
     */
    @Test
    public void workRequestIdTest() {
        // TODO: test workRequestId
    }

    /**
     * Test the property 'effectiveDate'
     */
    @Test
    public void effectiveDateTest() {
        // TODO: test effectiveDate
    }

    /**
     * Test the property 'errors'
     */
    @Test
    public void errorsTest() {
        // TODO: test errors
    }

}
