/*
 * Bill Pay Exchange Biller Management API
 * Biller Management Service
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Bill_Pay_Development_Support@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.developer.biller_management_client.model;

import org.junit.Test;


/**
 * Model tests for CardPaymentModel
 */
public class CardPaymentModelTest {
    private final CardPaymentModel model = new CardPaymentModel();

    /**
     * Model tests for CardPaymentModel
     */
    @Test
    public void testCardPaymentModel() {
        // TODO: test CardPaymentModel
    }

    /**
     * Test the property 'cardEnabled'
     */
    @Test
    public void cardEnabledTest() {
        // TODO: test cardEnabled
    }

    /**
     * Test the property 'cardNetworks'
     */
    @Test
    public void cardNetworksTest() {
        // TODO: test cardNetworks
    }

    /**
     * Test the property 'cardTypes'
     */
    @Test
    public void cardTypesTest() {
        // TODO: test cardTypes
    }

}
