/*
 * Bill Pay Exchange Biller Management API
 * Biller Management Service
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Bill_Pay_Development_Support@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.developer.biller_management_client.model;

import org.junit.Test;


/**
 * Model tests for ConsumerAuthenticationModel
 */
public class ConsumerAuthenticationModelTest {
    private final ConsumerAuthenticationModel model = new ConsumerAuthenticationModel();

    /**
     * Model tests for ConsumerAuthenticationModel
     */
    @Test
    public void testConsumerAuthenticationModel() {
        // TODO: test ConsumerAuthenticationModel
    }

    /**
     * Test the property 'recordAction'
     */
    @Test
    public void recordActionTest() {
        // TODO: test recordAction
    }

    /**
     * Test the property 'category'
     */
    @Test
    public void categoryTest() {
        // TODO: test category
    }

    /**
     * Test the property 'categoryLabel'
     */
    @Test
    public void categoryLabelTest() {
        // TODO: test categoryLabel
    }

    /**
     * Test the property 'dataType'
     */
    @Test
    public void dataTypeTest() {
        // TODO: test dataType
    }

    /**
     * Test the property 'maxLength'
     */
    @Test
    public void maxLengthTest() {
        // TODO: test maxLength
    }

    /**
     * Test the property 'notes'
     */
    @Test
    public void notesTest() {
        // TODO: test notes
    }

}
