/*
 * Bill Pay Exchange Biller Management API
 * Biller Management Service
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Bill_Pay_Development_Support@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.developer.biller_management_client.model;

import org.junit.Test;


/**
 * Model tests for ConvenienceFeeModel
 */
public class ConvenienceFeeModelTest {
    private final ConvenienceFeeModel model = new ConvenienceFeeModel();

    /**
     * Model tests for ConvenienceFeeModel
     */
    @Test
    public void testConvenienceFeeModel() {
        // TODO: test ConvenienceFeeModel
    }

    /**
     * Test the property 'recordAction'
     */
    @Test
    public void recordActionTest() {
        // TODO: test recordAction
    }

    /**
     * Test the property 'paymentType'
     */
    @Test
    public void paymentTypeTest() {
        // TODO: test paymentType
    }

    /**
     * Test the property 'flatFee'
     */
    @Test
    public void flatFeeTest() {
        // TODO: test flatFee
    }

    /**
     * Test the property 'percentFee'
     */
    @Test
    public void percentFeeTest() {
        // TODO: test percentFee
    }

}
