/*
 * Bill Pay Exchange Biller Management API
 * Biller Management Service
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Bill_Pay_Development_Support@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.developer.biller_management_client.model;

import org.junit.Test;


/**
 * Model tests for DeactivationModel
 */
public class DeactivationModelTest {
    private final DeactivationModel model = new DeactivationModel();

    /**
     * Model tests for DeactivationModel
     */
    @Test
    public void testDeactivationModel() {
        // TODO: test DeactivationModel
    }

    /**
     * Test the property 'deactivationReasonCode'
     */
    @Test
    public void deactivationReasonCodeTest() {
        // TODO: test deactivationReasonCode
    }

    /**
     * Test the property 'deactivationNotes'
     */
    @Test
    public void deactivationNotesTest() {
        // TODO: test deactivationNotes
    }

}
