/*
 * Bill Pay Exchange Biller Management API
 * Biller Management Service
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Bill_Pay_Development_Support@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.developer.biller_management_client.model;

import org.junit.Test;


/**
 * Model tests for GeneralModel
 */
public class GeneralModelTest {
    private final GeneralModel model = new GeneralModel();

    /**
     * Model tests for GeneralModel
     */
    @Test
    public void testGeneralModel() {
        // TODO: test GeneralModel
    }

    /**
     * Test the property 'billerId'
     */
    @Test
    public void billerIdTest() {
        // TODO: test billerId
    }

    /**
     * Test the property 'billerLogoUrl'
     */
    @Test
    public void billerLogoUrlTest() {
        // TODO: test billerLogoUrl
    }

    /**
     * Test the property 'billerShortName'
     */
    @Test
    public void billerShortNameTest() {
        // TODO: test billerShortName
    }

    /**
     * Test the property 'convenienceFee'
     */
    @Test
    public void convenienceFeeTest() {
        // TODO: test convenienceFee
    }

    /**
     * Test the property 'estimatedPostingHour'
     */
    @Test
    public void estimatedPostingHourTest() {
        // TODO: test estimatedPostingHour
    }

    /**
     * Test the property 'termsAndConditions'
     */
    @Test
    public void termsAndConditionsTest() {
        // TODO: test termsAndConditions
    }

}
