/*
 * Bill Pay Exchange Biller Management API
 * Biller Management Service
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Bill_Pay_Development_Support@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.developer.biller_management_client.model;

import org.junit.Test;


/**
 * Model tests for ServiceRelationshipModel
 */
public class ServiceRelationshipModelTest {
    private final ServiceRelationshipModel model = new ServiceRelationshipModel();

    /**
     * Model tests for ServiceRelationshipModel
     */
    @Test
    public void testServiceRelationshipModel() {
        // TODO: test ServiceRelationshipModel
    }

    /**
     * Test the property 'recordAction'
     */
    @Test
    public void recordActionTest() {
        // TODO: test recordAction
    }

    /**
     * Test the property 'bspId'
     */
    @Test
    public void bspIdTest() {
        // TODO: test bspId
    }

    /**
     * Test the property 'serviceType'
     */
    @Test
    public void serviceTypeTest() {
        // TODO: test serviceType
    }

}
