/*
 * Bill Pay Exchange Biller Management API
 * Biller Management Service
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Bill_Pay_Development_Support@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.developer.biller_management_client.model;

import org.junit.Test;


/**
 * Model tests for ServerError
 */
public class ServerErrorTest {
    private final ServerError model = new ServerError();

    /**
     * Model tests for ServerError
     */
    @Test
    public void testServerError() {
        // TODO: test ServerError
    }

    /**
     * Test the property 'errors'
     */
    @Test
    public void errorsTest() {
        // TODO: test errors
    }

}
