/*
 * Bill Pay Exchange Biller Management API
 * Biller Management Service
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Bill_Pay_Development_Support@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.developer.biller_management_client.model;

import org.junit.Test;


/**
 * Model tests for ServerErrorErrors
 */
public class ServerErrorErrorsTest {
    private final ServerErrorErrors model = new ServerErrorErrors();

    /**
     * Model tests for ServerErrorErrors
     */
    @Test
    public void testServerErrorErrors() {
        // TODO: test ServerErrorErrors
    }

    /**
     * Test the property 'error'
     */
    @Test
    public void errorTest() {
        // TODO: test error
    }

}
