/*
 * Bill Pay Exchange Biller Management API
 * Biller Management Service
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Bill_Pay_Development_Support@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.developer.biller_management_client.model;

import org.junit.Test;


/**
 * Model tests for ServiceAreaModel
 */
public class ServiceAreaModelTest {
    private final ServiceAreaModel model = new ServiceAreaModel();

    /**
     * Model tests for ServiceAreaModel
     */
    @Test
    public void testServiceAreaModel() {
        // TODO: test ServiceAreaModel
    }

    /**
     * Test the property 'zipCodes'
     */
    @Test
    public void zipCodesTest() {
        // TODO: test zipCodes
    }

}
