/*
 * Bill Pay Exchange Biller Management API
 * Biller Management Service
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Bill_Pay_Development_Support@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.developer.biller_management_client.model;

import org.junit.Test;


/**
 * Model tests for UserErrorModel
 */
public class UserErrorModelTest {
    private final UserErrorModel model = new UserErrorModel();

    /**
     * Model tests for UserErrorModel
     */
    @Test
    public void testUserErrorModel() {
        // TODO: test UserErrorModel
    }

    /**
     * Test the property 'code'
     */
    @Test
    public void codeTest() {
        // TODO: test code
    }

    /**
     * Test the property 'message'
     */
    @Test
    public void messageTest() {
        // TODO: test message
    }

}
