/*
 * Bill Pay Exchange Biller Management API
 * Biller Management Service
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: Bill_Pay_Development_Support@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.developer.biller_management_client.api;

import com.mastercard.developer.biller_management_client.ApiException;
import com.mastercard.developer.biller_management_client.model.BillerManagementRequest;
import com.mastercard.developer.biller_management_client.model.BillerManagementResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.List;

/**
 * API tests for BillerManagementControllerApi
 */
@Ignore
public class BillerManagementControllerApiTest {

    private final BillerManagementControllerApi api = new BillerManagementControllerApi();

    
    /**
     * Add, edit or deactivate one or multiple Billers in Biller Pay Exchange
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void processBillerUploadPostRequestUsingPOSTTest() throws ApiException {
        List<BillerManagementRequest> billerManagementRequest = null;
        List<BillerManagementResponse> response = api.processBillerUploadPostRequestUsingPOST(billerManagementRequest);

        // TODO: test validations
    }
    
}
