/*
 * Bill Pay Exchange Biller Management API
 * Biller Management Service
 *
 * OpenAPI spec version: 1.0.0
 * Contact: Bill_Pay_Development_Support@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.developer.biller_management_client.api;

import com.google.gson.reflect.TypeToken;
import com.mastercard.developer.biller_management_client.*;
import com.mastercard.developer.biller_management_client.model.BillerManagementRequest;
import com.mastercard.developer.biller_management_client.model.BillerManagementResponse;

import java.io.IOException;
import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class BillerManagementControllerApi {
    private ApiClient apiClient;

    public BillerManagementControllerApi() {
        this(Configuration.getDefaultApiClient());
    }

    public BillerManagementControllerApi(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return apiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    /**
     * Build call for processBillerUploadPostRequestUsingPOST
     * @param billerManagementRequest Billers to be uploaded to Biller Pay Exchange (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call processBillerUploadPostRequestUsingPOSTCall(List<BillerManagementRequest> billerManagementRequest, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = billerManagementRequest;

        // create path and map variables
        String localVarPath = "/billers";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();
        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if (progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        return apiClient.buildCall(localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }

    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call processBillerUploadPostRequestUsingPOSTValidateBeforeCall(List<BillerManagementRequest> billerManagementRequest, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'billerManagementRequest' is set
        if (billerManagementRequest == null) {
            throw new ApiException("Missing the required parameter 'billerManagementRequest' when calling processBillerUploadPostRequestUsingPOST(Async)");
        }
        

        com.squareup.okhttp.Call call = processBillerUploadPostRequestUsingPOSTCall(billerManagementRequest, progressListener, progressRequestListener);
        return call;

    }

    /**
     * Add, edit or deactivate one or multiple Billers in Biller Pay Exchange
     * 
     * @param billerManagementRequest Billers to be uploaded to Biller Pay Exchange (required)
     * @return List&lt;BillerManagementResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public List<BillerManagementResponse> processBillerUploadPostRequestUsingPOST(List<BillerManagementRequest> billerManagementRequest) throws ApiException {
        ApiResponse<List<BillerManagementResponse>> resp = processBillerUploadPostRequestUsingPOSTWithHttpInfo(billerManagementRequest);
        return resp.getData();
    }

    /**
     * Add, edit or deactivate one or multiple Billers in Biller Pay Exchange
     * 
     * @param billerManagementRequest Billers to be uploaded to Biller Pay Exchange (required)
     * @return ApiResponse&lt;List&lt;BillerManagementResponse&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<List<BillerManagementResponse>> processBillerUploadPostRequestUsingPOSTWithHttpInfo(List<BillerManagementRequest> billerManagementRequest) throws ApiException {
        com.squareup.okhttp.Call call = processBillerUploadPostRequestUsingPOSTValidateBeforeCall(billerManagementRequest, null, null);
        Type localVarReturnType = new TypeToken<List<BillerManagementResponse>>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Add, edit or deactivate one or multiple Billers in Biller Pay Exchange (asynchronously)
     * 
     * @param billerManagementRequest Billers to be uploaded to Biller Pay Exchange (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call processBillerUploadPostRequestUsingPOSTAsync(List<BillerManagementRequest> billerManagementRequest, final ApiCallback<List<BillerManagementResponse>> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = processBillerUploadPostRequestUsingPOSTValidateBeforeCall(billerManagementRequest, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<List<BillerManagementResponse>>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
}
