/*
 * Bill Pay Exchange Biller Management API
 * Biller Management Service
 *
 * OpenAPI spec version: 1.0.0
 * Contact: Bill_Pay_Development_Support@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.developer.biller_management_client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Response Model class for Biller Management API
 */
@ApiModel(description = "Response Model class for Biller Management API")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-01-30T10:30:57.815-06:00[America/Chicago]")
public class BillerManagementResponse {
  public static final String SERIALIZED_NAME_ACTION = "action";
  @SerializedName(SERIALIZED_NAME_ACTION)
  private String action;

  public static final String SERIALIZED_NAME_BILLER_ID = "billerId";
  @SerializedName(SERIALIZED_NAME_BILLER_ID)
  private String billerId;

  public static final String SERIALIZED_NAME_STATUS_INDICATOR = "statusIndicator";
  @SerializedName(SERIALIZED_NAME_STATUS_INDICATOR)
  private String statusIndicator;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_WORK_REQUEST_ID = "workRequestId";
  @SerializedName(SERIALIZED_NAME_WORK_REQUEST_ID)
  private String workRequestId;

  public static final String SERIALIZED_NAME_EFFECTIVE_DATE = "effectiveDate";
  @SerializedName(SERIALIZED_NAME_EFFECTIVE_DATE)
  private String effectiveDate;

  public static final String SERIALIZED_NAME_ERRORS = "errors";
  @SerializedName(SERIALIZED_NAME_ERRORS)
  private List<UserErrorModel> errors = null;

  public BillerManagementResponse action(String action) {
    this.action = action;
    return this;
  }

   /**
   * Action
   * @return action
  **/
  @ApiModelProperty(required = true, value = "Action")
  public String getAction() {
    return action;
  }

  public void setAction(String action) {
    this.action = action;
  }

  public BillerManagementResponse billerId(String billerId) {
    this.billerId = billerId;
    return this;
  }

   /**
   * Biller ID
   * @return billerId
  **/
  @ApiModelProperty(value = "Biller ID")
  public String getBillerId() {
    return billerId;
  }

  public void setBillerId(String billerId) {
    this.billerId = billerId;
  }

  public BillerManagementResponse statusIndicator(String statusIndicator) {
    this.statusIndicator = statusIndicator;
    return this;
  }

   /**
   * Status Indicator
   * @return statusIndicator
  **/
  @ApiModelProperty(required = true, value = "Status Indicator")
  public String getStatusIndicator() {
    return statusIndicator;
  }

  public void setStatusIndicator(String statusIndicator) {
    this.statusIndicator = statusIndicator;
  }

  public BillerManagementResponse description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Description
   * @return description
  **/
  @ApiModelProperty(required = true, value = "Description")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public BillerManagementResponse workRequestId(String workRequestId) {
    this.workRequestId = workRequestId;
    return this;
  }

   /**
   * Biller Work Request Id
   * @return workRequestId
  **/
  @ApiModelProperty(value = "Biller Work Request Id")
  public String getWorkRequestId() {
    return workRequestId;
  }

  public void setWorkRequestId(String workRequestId) {
    this.workRequestId = workRequestId;
  }

  public BillerManagementResponse effectiveDate(String effectiveDate) {
    this.effectiveDate = effectiveDate;
    return this;
  }

   /**
   * Effective Date
   * @return effectiveDate
  **/
  @ApiModelProperty(required = true, value = "Effective Date")
  public String getEffectiveDate() {
    return effectiveDate;
  }

  public void setEffectiveDate(String effectiveDate) {
    this.effectiveDate = effectiveDate;
  }

  public BillerManagementResponse errors(List<UserErrorModel> errors) {
    this.errors = errors;
    return this;
  }

  public BillerManagementResponse addErrorsItem(UserErrorModel errorsItem) {
    if (this.errors == null) {
      this.errors = new ArrayList<UserErrorModel>();
    }
    this.errors.add(errorsItem);
    return this;
  }

   /**
   * Error List
   * @return errors
  **/
  @ApiModelProperty(value = "Error List")
  public List<UserErrorModel> getErrors() {
    return errors;
  }

  public void setErrors(List<UserErrorModel> errors) {
    this.errors = errors;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BillerManagementResponse billerManagementResponse = (BillerManagementResponse) o;
    return Objects.equals(this.action, billerManagementResponse.action) &&
        Objects.equals(this.billerId, billerManagementResponse.billerId) &&
        Objects.equals(this.statusIndicator, billerManagementResponse.statusIndicator) &&
        Objects.equals(this.description, billerManagementResponse.description) &&
        Objects.equals(this.workRequestId, billerManagementResponse.workRequestId) &&
        Objects.equals(this.effectiveDate, billerManagementResponse.effectiveDate) &&
        Objects.equals(this.errors, billerManagementResponse.errors);
  }

  @Override
  public int hashCode() {
    return Objects.hash(action, billerId, statusIndicator, description, workRequestId, effectiveDate, errors);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BillerManagementResponse {\n");

    sb.append("    action: ").append(toIndentedString(action)).append("\n");
    sb.append("    billerId: ").append(toIndentedString(billerId)).append("\n");
    sb.append("    statusIndicator: ").append(toIndentedString(statusIndicator)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    workRequestId: ").append(toIndentedString(workRequestId)).append("\n");
    sb.append("    effectiveDate: ").append(toIndentedString(effectiveDate)).append("\n");
    sb.append("    errors: ").append(toIndentedString(errors)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

