/*
 * Bill Pay Exchange Biller Management API
 * Biller Management Service
 *
 * OpenAPI spec version: 1.0.0
 * Contact: Bill_Pay_Development_Support@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.developer.biller_management_client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Deactivation Reason and Note Model, only required when action is &#39;Deactivate&#39;
 */
@ApiModel(description = "Deactivation Reason and Note Model, only required when action is 'Deactivate'")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-01-30T10:30:57.815-06:00[America/Chicago]")
public class DeactivationModel {
  public static final String SERIALIZED_NAME_DEACTIVATION_REASON_CODE = "deactivationReasonCode";
  @SerializedName(SERIALIZED_NAME_DEACTIVATION_REASON_CODE)
  private String deactivationReasonCode;

  public static final String SERIALIZED_NAME_DEACTIVATION_NOTES = "deactivationNotes";
  @SerializedName(SERIALIZED_NAME_DEACTIVATION_NOTES)
  private String deactivationNotes;

  public DeactivationModel deactivationReasonCode(String deactivationReasonCode) {
    this.deactivationReasonCode = deactivationReasonCode;
    return this;
  }

   /**
   * Deactivation Reason Code, avaliable values are: BCON, BMIG, LVOL, RBLR, OTHR
   * @return deactivationReasonCode
  **/
  @ApiModelProperty(example = "BCON", required = true, value = "Deactivation Reason Code, avaliable values are: BCON, BMIG, LVOL, RBLR, OTHR")
  public String getDeactivationReasonCode() {
    return deactivationReasonCode;
  }

  public void setDeactivationReasonCode(String deactivationReasonCode) {
    this.deactivationReasonCode = deactivationReasonCode;
  }

  public DeactivationModel deactivationNotes(String deactivationNotes) {
    this.deactivationNotes = deactivationNotes;
    return this;
  }

   /**
   * Deactivation Note, max length 1000 characters
   * @return deactivationNotes
  **/
  @ApiModelProperty(example = "Deactiviation Notes for Wanda Auto", required = true, value = "Deactivation Note, max length 1000 characters")
  public String getDeactivationNotes() {
    return deactivationNotes;
  }

  public void setDeactivationNotes(String deactivationNotes) {
    this.deactivationNotes = deactivationNotes;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeactivationModel deactivationModel = (DeactivationModel) o;
    return Objects.equals(this.deactivationReasonCode, deactivationModel.deactivationReasonCode) &&
        Objects.equals(this.deactivationNotes, deactivationModel.deactivationNotes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(deactivationReasonCode, deactivationNotes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeactivationModel {\n");

    sb.append("    deactivationReasonCode: ").append(toIndentedString(deactivationReasonCode)).append("\n");
    sb.append("    deactivationNotes: ").append(toIndentedString(deactivationNotes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

