/*
 * Bill Pay Exchange Biller Management API
 * Biller Management Service
 *
 * OpenAPI spec version: 1.0.0
 * Contact: Bill_Pay_Development_Support@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.developer.biller_management_client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Model class for Biller work request general section
 */
@ApiModel(description = "Model class for Biller work request general section")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-01-30T10:30:57.815-06:00[America/Chicago]")
public class GeneralModel {
  public static final String SERIALIZED_NAME_BILLER_ID = "billerId";
  @SerializedName(SERIALIZED_NAME_BILLER_ID)
  private String billerId;

  public static final String SERIALIZED_NAME_BILLER_LOGO_URL = "billerLogoUrl";
  @SerializedName(SERIALIZED_NAME_BILLER_LOGO_URL)
  private String billerLogoUrl;

  public static final String SERIALIZED_NAME_BILLER_SHORT_NAME = "billerShortName";
  @SerializedName(SERIALIZED_NAME_BILLER_SHORT_NAME)
  private String billerShortName;

  public static final String SERIALIZED_NAME_CONVENIENCE_FEE = "convenienceFee";
  @SerializedName(SERIALIZED_NAME_CONVENIENCE_FEE)
  private String convenienceFee;

  public static final String SERIALIZED_NAME_ESTIMATED_POSTING_HOUR = "estimatedPostingHour";
  @SerializedName(SERIALIZED_NAME_ESTIMATED_POSTING_HOUR)
  private String estimatedPostingHour;

  public static final String SERIALIZED_NAME_TERMS_AND_CONDITIONS = "termsAndConditions";
  @SerializedName(SERIALIZED_NAME_TERMS_AND_CONDITIONS)
  private String termsAndConditions;

  public GeneralModel billerId(String billerId) {
    this.billerId = billerId;
    return this;
  }

   /**
   * Biller Id, 10 digit numeric value
   * @return billerId
  **/
  @ApiModelProperty(example = "0001234567", required = true, value = "Biller Id, 10 digit numeric value")
  public String getBillerId() {
    return billerId;
  }

  public void setBillerId(String billerId) {
    this.billerId = billerId;
  }

  public GeneralModel billerLogoUrl(String billerLogoUrl) {
    this.billerLogoUrl = billerLogoUrl;
    return this;
  }

   /**
   * Biller Logo URL, max length 512 characters
   * @return billerLogoUrl
  **/
  @ApiModelProperty(example = "www.wandaauto.com", required = true, value = "Biller Logo URL, max length 512 characters")
  public String getBillerLogoUrl() {
    return billerLogoUrl;
  }

  public void setBillerLogoUrl(String billerLogoUrl) {
    this.billerLogoUrl = billerLogoUrl;
  }

  public GeneralModel billerShortName(String billerShortName) {
    this.billerShortName = billerShortName;
    return this;
  }

   /**
   * Biller ShortName, max length 35 characters
   * @return billerShortName
  **/
  @ApiModelProperty(example = "Wanda Auto", required = true, value = "Biller ShortName, max length 35 characters")
  public String getBillerShortName() {
    return billerShortName;
  }

  public void setBillerShortName(String billerShortName) {
    this.billerShortName = billerShortName;
  }

  public GeneralModel convenienceFee(String convenienceFee) {
    this.convenienceFee = convenienceFee;
    return this;
  }

   /**
   * Convenience Fee Flag, avaliable values are: Yes, No
   * @return convenienceFee
  **/
  @ApiModelProperty(example = "Yes", required = true, value = "Convenience Fee Flag, avaliable values are: Yes, No")
  public String getConvenienceFee() {
    return convenienceFee;
  }

  public void setConvenienceFee(String convenienceFee) {
    this.convenienceFee = convenienceFee;
  }

  public GeneralModel estimatedPostingHour(String estimatedPostingHour) {
    this.estimatedPostingHour = estimatedPostingHour;
    return this;
  }

   /**
   * Estimated Posting Number, max length 2 numeric value
   * @return estimatedPostingHour
  **/
  @ApiModelProperty(example = "10", required = true, value = "Estimated Posting Number, max length 2 numeric value")
  public String getEstimatedPostingHour() {
    return estimatedPostingHour;
  }

  public void setEstimatedPostingHour(String estimatedPostingHour) {
    this.estimatedPostingHour = estimatedPostingHour;
  }

  public GeneralModel termsAndConditions(String termsAndConditions) {
    this.termsAndConditions = termsAndConditions;
    return this;
  }

   /**
   * Terms And Conditions Text
   * @return termsAndConditions
  **/
  @ApiModelProperty(example = "Terms And Conditions", required = true, value = "Terms And Conditions Text")
  public String getTermsAndConditions() {
    return termsAndConditions;
  }

  public void setTermsAndConditions(String termsAndConditions) {
    this.termsAndConditions = termsAndConditions;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GeneralModel generalModel = (GeneralModel) o;
    return Objects.equals(this.billerId, generalModel.billerId) &&
        Objects.equals(this.billerLogoUrl, generalModel.billerLogoUrl) &&
        Objects.equals(this.billerShortName, generalModel.billerShortName) &&
        Objects.equals(this.convenienceFee, generalModel.convenienceFee) &&
        Objects.equals(this.estimatedPostingHour, generalModel.estimatedPostingHour) &&
        Objects.equals(this.termsAndConditions, generalModel.termsAndConditions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(billerId, billerLogoUrl, billerShortName, convenienceFee, estimatedPostingHour, termsAndConditions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GeneralModel {\n");

    sb.append("    billerId: ").append(toIndentedString(billerId)).append("\n");
    sb.append("    billerLogoUrl: ").append(toIndentedString(billerLogoUrl)).append("\n");
    sb.append("    billerShortName: ").append(toIndentedString(billerShortName)).append("\n");
    sb.append("    convenienceFee: ").append(toIndentedString(convenienceFee)).append("\n");
    sb.append("    estimatedPostingHour: ").append(toIndentedString(estimatedPostingHour)).append("\n");
    sb.append("    termsAndConditions: ").append(toIndentedString(termsAndConditions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

