/*
 * Bill Pay Exchange Biller Management API
 * Biller Management Service
 *
 * OpenAPI spec version: 1.0.0
 * Contact: Bill_Pay_Development_Support@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.developer.biller_management_client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * ServiceAreaModel
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-01-30T10:30:57.815-06:00[America/Chicago]")
public class ServiceAreaModel {
  public static final String SERIALIZED_NAME_ZIP_CODES = "zipCodes";
  @SerializedName(SERIALIZED_NAME_ZIP_CODES)
  private String zipCodes;

  public ServiceAreaModel zipCodes(String zipCodes) {
    this.zipCodes = zipCodes;
    return this;
  }

   /**
   * Zip Codes, comma separated 5 digit numeric values
   * @return zipCodes
  **/
  @ApiModelProperty(example = "63301, 63302, 63303", required = true, value = "Zip Codes, comma separated 5 digit numeric values")
  public String getZipCodes() {
    return zipCodes;
  }

  public void setZipCodes(String zipCodes) {
    this.zipCodes = zipCodes;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceAreaModel serviceAreaModel = (ServiceAreaModel) o;
    return Objects.equals(this.zipCodes, serviceAreaModel.zipCodes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(zipCodes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceAreaModel {\n");

    sb.append("    zipCodes: ").append(toIndentedString(zipCodes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

